/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as games from "../games.js";
import type * as platforms from "../platforms.js";
import type * as tournamentFormats from "../tournamentFormats.js";
import type * as tournaments from "../tournaments.js";
import type * as tournamentStages from "../tournamentStages.js";
import type * as tournamentTypes from "../tournamentTypes.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  games: typeof games;
  platforms: typeof platforms;
  tournamentFormats: typeof tournamentFormats;
  tournaments: typeof tournaments;
  tournamentStages: typeof tournamentStages;
  tournamentTypes: typeof tournamentTypes;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
